std = "lua51"
codes = true
max_line_length = false
ignore = {
  "211/ADDON_NAME",
  "212/self"
}

exclude_files = {
  ".claude/**",
  ".devcontainer/**",
  "Libs/**"
}

-- Test files run under Busted, which injects describe/it/assert/spy/etc.
files["spec"] = {
  std = "lua51+busted"
}

globals = {
  "MacroFrame",
  "MuscleMemory",
  "MuscleMemoryDB",
  "SLASH_MUSCLEMEMORY1",
  "SLASH_MUSCLEMEMORY2",
  "SlashCmdList",
  "StaticPopupDialogs"
}

read_globals = {
  "ADDON_LOADED",
  "LibStub",
  "C_ActionBar",
  "C_AddOns",
  "C_AssistedCombat",
  "C_CreatureInfo",
  "C_EquipmentSet",
  "C_Item",
  "C_Macro",
  "C_MountJournal",
  "C_PetJournal",
  "C_Spell",
  "C_SpellBook",
  "C_Timer",
  "C_TooltipInfo",
  "C_TransmogOutfitInfo",
  "C_ToyBox",
  "CANCEL",
  "ClearCursor",
  "CreateFrame",
  "CreateScrollBoxLinearView",
  "DELETE",
  "DONE",
  "Enum",
  "MenuUtil",
  "ScrollUtil",
  "UISpecialFrames",
  "tinsert",
  "GameFontDisableSmall",
  "GameFontHighlight",
  "GameFontNormalLarge",
  "GameFontNormalSmall",
  "GameTooltip",
  "GetActionInfo",
  "GetActionText",
  "GetActionTexture",
  "GetBindingKey",
  "GetBindingText",
  "GetCVar",
  "SetCVar",
  "Screenshot",
  "MacroFrameTab2",
  "ShowUIPanel",
  "HideUIPanel",
  "CreateMacro",
  "DeleteMacro",
  "EditMacro",
  "FindBaseSpellByID",
  "GetCursorInfo",
  "GetFlyoutInfo",
  "GetFlyoutSlotInfo",
  "GetItemInfo",
  "GetItemCount",
  "GetLocale",
  "GetMacroInfo",
  "GetMacroIndexByName",
  "GetNumMacros",
  "GetNumSpecializations",
  "GetNumSpecializationsForClassID",
  "GetNumShapeshiftForms",
  "GetRealmName",
  "GetSpecialization",
  "GetSpecializationInfo",
  "GetSpecializationInfoByID",
  "GetSpecializationInfoForClassID",
  "GetSpecializationRole",
  "GetSpellInfo",
  "HasAction",
  "InCombatLockdown",
  "LOCALIZED_CLASS_NAMES_MALE",
  "FACTION_ALLIANCE",
  "FACTION_HORDE",
  "IsEquippedItem",
  "IsPlayerSpell",
  "IsSpellKnown",
  "IsUsableItem",
  "MAX_ACCOUNT_MACROS",
  "MAX_CHARACTER_MACROS",
  "PickupAction",
  "PickupItem",
  "PickupMacro",
  "PickupSpell",
  "PlaceAction",
  "PlayerHasToy",
  "ReloadUI",
  "StaticPopup_Hide",
  "StaticPopup_Show",
  "STATICPOPUP_NUMDIALOGS",
  "TooltipUtil",
  "UIParent",
  "UnitClass",
  "UnitFactionGroup",
  "UnitLevel",
  "UnitName",
  "UnitRace",
  "print",
  "time"
}
