local addon = require("spec.helpers.addon")

describe("Flyouts", function()
  local MM, stubs
  before_each(function()
    MM, stubs = addon.fresh()
  end)

  describe("GetInfo", function()
    it("returns nil for a nil id or unknown flyout", function()
      assert.is_nil(MM.Flyouts.GetInfo(nil))
      assert.is_nil(MM.Flyouts.GetInfo(123))
    end)

    it("reads name, slot count and known state", function()
      stubs:setFlyout(12, { name = "Teleports", numSlots = 3, known = true })
      local info = MM.Flyouts.GetInfo(12)
      assert.equals("Teleports", info.name)
      assert.equals(3, info.numSlots)
      assert.is_true(info.isKnown)
    end)

    it("borrows the icon from the first readable slot spell", function()
      stubs:setSpell(101, { name = "Teleport: Stormwind", icon = 135739 })
      stubs:setFlyout(12, { name = "Teleports", slots = { 101 } })
      assert.equals(135739, MM.Flyouts.GetInfo(12).icon)
    end)
  end)

  describe("IsKnown", function()
    it("is true for a known flyout", function()
      stubs:setFlyout(12, { known = true })
      assert.is_true(MM.Flyouts.IsKnown(12))
    end)

    it("is false for an unknown flyout", function()
      stubs:setFlyout(12, { known = false })
      assert.is_false(MM.Flyouts.IsKnown(12))
    end)

    it("is falsey for a flyout that does not exist", function()
      assert.is_falsy(MM.Flyouts.IsKnown(123))
    end)
  end)

  describe("Pickup", function()
    it("finds the flyout in the spellbook and picks it onto the cursor", function()
      stubs:setFlyout(12, { name = "Teleports" })
      assert.is_true(MM.Flyouts.Pickup(12))
      assert.same({ type = "flyout", id = 12 }, stubs.world.cursor)
    end)

    it("returns false when the flyout is not in the spellbook", function()
      assert.is_false(MM.Flyouts.Pickup(999))
      assert.is_nil(stubs.world.cursor)
    end)
  end)

  describe("Resolver", function()
    it("resolves a known flyout with its icon and availability", function()
      stubs:setSpell(101, { name = "Teleport: Stormwind", icon = 135739 })
      stubs:setFlyout(12, { name = "Teleports", slots = { 101 }, known = true })
      local resolved = MM.Resolver:ResolveAction({ type = "flyout", id = 12 })
      assert.equals("flyout", resolved.kind)
      assert.equals("Teleports", resolved.label)
      assert.equals(135739, resolved.icon)
      assert.is_true(resolved.pickupAvailable)
    end)

    it("refuses an unknown flyout when availability is required", function()
      stubs:setFlyout(12, { name = "Teleports", known = false })
      local resolved, reason = MM.Resolver:ResolveAction({ type = "flyout", id = 12 }, { requireAvailable = true })
      assert.is_nil(resolved)
      assert.equals("flyout not known", reason)
    end)

    it("reports a flyout that does not exist at all", function()
      local resolved, reason = MM.Resolver:ResolveAction({ type = "flyout", id = 999 })
      assert.is_nil(resolved)
      assert.equals("flyout not found", reason)
    end)
  end)

  describe("apply round-trip", function()
    it("captures, resolves and re-places a flyout on the bar", function()
      stubs:setFlyout(12, { name = "Teleports" })
      stubs:setSlot(8, { actionType = "flyout", id = 12 })

      local ok = MM.Capture:CaptureSlot("Core", 8)
      assert.is_true(ok)

      stubs.world.slots[8] = nil
      assert.is_true(MM.Applier:ApplyProfile())
      assert.equals("flyout", stubs.world.slots[8].actionType)
      assert.equals(12, stubs.world.slots[8].id)
      assert.is_nil(stubs.world.cursor)
    end)
  end)
end)
