local addon = require("spec.helpers.addon")

describe("Macros", function()
  local MM, stubs
  before_each(function()
    MM, stubs = addon.load()
  end)

  describe("HashBody", function()
    it("is deterministic and 8 hex chars", function()
      local hash = MM.Macros.HashBody("/cast Fireball")
      assert.equals(hash, MM.Macros.HashBody("/cast Fireball"))
      assert.matches("^%x%x%x%x%x%x%x%x$", hash)
    end)

    it("differs for different bodies", function()
      assert.are_not.equal(MM.Macros.HashBody("/cast A"), MM.Macros.HashBody("/cast B"))
    end)

    it("treats nil as the empty string", function()
      assert.equals(MM.Macros.HashBody(""), MM.Macros.HashBody(nil))
    end)
  end)

  describe("GetMacroScope", function()
    it("classifies low indices as global and high ones as character", function()
      assert.equals("global", MM.Macros.GetMacroScope(2, 5))
      assert.equals("global", MM.Macros.GetMacroScope(50, 0))
      assert.equals("character", MM.Macros.GetMacroScope(121, 2))
    end)
  end)

  describe("Scan", function()
    it("returns an empty list when the macro API is unavailable", function()
      local _, _, env = addon.load()
      env.GetNumMacros = nil
      assert.same({}, MM.Macros.Scan())
    end)

    it("scans global and character macros with their scopes and indices", function()
      stubs:addGlobalMacro({ name = "A", icon = 1, body = "/cast A" })
      stubs:addGlobalMacro({ name = "B", icon = 2, body = "/cast B" })
      stubs:addCharacterMacro({ name = "C", icon = 3, body = "/cast C" })

      local macros = MM.Macros.Scan()
      assert.equals(3, #macros)
      assert.equals("global", macros[1].scope)
      assert.equals("global", macros[2].scope)
      assert.equals("character", macros[3].scope)
      assert.equals(121, macros[3].index)
      assert.equals(MM.Macros.HashBody("/cast C"), macros[3].bodyHash)
    end)
  end)

  describe("FindUniqueByName", function()
    before_each(function()
      stubs:addGlobalMacro({ name = "Solo", body = "/cast Solo" })
      stubs:addGlobalMacro({ name = "Dup", body = "/one" })
      stubs:addGlobalMacro({ name = "Dup", body = "/two" })
    end)

    it("returns the single match", function()
      local macro = MM.Macros.FindUniqueByName("Solo")
      assert.equals("Solo", macro.name)
    end)

    it("reports ambiguity", function()
      local macro, reason = MM.Macros.FindUniqueByName("Dup")
      assert.is_nil(macro)
      assert.equals("macro name is ambiguous", reason)
    end)

    it("reports a missing name", function()
      local macro, reason = MM.Macros.FindUniqueByName("Nope")
      assert.is_nil(macro)
      assert.equals("macro name not found", reason)
    end)

    it("reports an unavailable name", function()
      local macro, reason = MM.Macros.FindUniqueByName(nil)
      assert.is_nil(macro)
      assert.equals("macro name unavailable", reason)
    end)
  end)

  describe("Resolve", function()
    before_each(function()
      stubs:addGlobalMacro({ name = "A", body = "/cast A" })
      stubs:addGlobalMacro({ name = "B", body = "/cast B" })
      stubs:addCharacterMacro({ name = "C", body = "/cast C" })
    end)

    it("requires a body hash", function()
      local macro, reason = MM.Macros.Resolve({})
      assert.is_nil(macro)
      assert.equals("macro reference has no body hash", reason)
    end)

    it("matches on index hint plus body hash first", function()
      local macro = MM.Macros.Resolve({ indexHint = 2, bodyHash = MM.Macros.HashBody("/cast B"), scope = "global" })
      assert.equals(2, macro.index)
      assert.equals("B", macro.name)
    end)

    it("falls back to scope plus body hash when the index moved", function()
      local macro = MM.Macros.Resolve({ indexHint = 99, bodyHash = MM.Macros.HashBody("/cast A"), scope = "global" })
      assert.equals(1, macro.index)
    end)

    it("falls back to body hash alone when scope no longer matches", function()
      local macro = MM.Macros.Resolve({ bodyHash = MM.Macros.HashBody("/cast A"), scope = "character" })
      assert.equals(1, macro.index)
    end)

    it("reports a miss when no body hash matches", function()
      local macro, reason = MM.Macros.Resolve({ bodyHash = "deadbeef" })
      assert.is_nil(macro)
      assert.equals("macro body hash not found", reason)
    end)
  end)
end)
