local addon = require("spec.helpers.addon")

describe("Mounts", function()
  local MM, stubs
  before_each(function()
    MM, stubs = addon.load()
  end)

  describe("GetInfo", function()
    it("returns nil for a nil id or unknown mount", function()
      assert.is_nil(MM.Mounts.GetInfo(nil))
      assert.is_nil(MM.Mounts.GetInfo(123))
    end)

    it("reads name, spellId, icon and collected state", function()
      stubs:setMount(219, { name = "Mechanostrider", spellId = 17453, icon = 132248, collected = true })
      local info = MM.Mounts.GetInfo(219)
      assert.equals("Mechanostrider", info.name)
      assert.equals(17453, info.spellId)
      assert.equals(132248, info.icon)
      assert.is_true(info.isCollected)
    end)
  end)

  describe("IsKnown", function()
    it("is true for a collected mount", function()
      stubs:setMount(219, { collected = true })
      assert.is_true(MM.Mounts.IsKnown(219))
    end)

    it("is false for an uncollected mount", function()
      stubs:setMount(219, { collected = false })
      assert.is_false(MM.Mounts.IsKnown(219))
    end)

    it("is falsey for an unknown mount", function()
      assert.is_falsy(MM.Mounts.IsKnown(123))
    end)
  end)

  describe("Pickup", function()
    it("picks the mount's summon spell up onto the cursor", function()
      stubs:setMount(219, { spellId = 17453 })
      assert.is_true(MM.Mounts.Pickup(219))
      assert.same({ type = "spell", id = 17453 }, stubs.world.cursor)
    end)

    it("returns false for a mount that is not in the journal", function()
      assert.is_false(MM.Mounts.Pickup(123))
      assert.is_nil(stubs.world.cursor)
    end)
  end)

  -- The "Summon Random Favorite Mount" button reports a sentinel id (268435455)
  -- on the action bar and has no journal entry, so it is described via spell 150544.
  describe("Summon Random Favorite Mount", function()
    before_each(function()
      stubs:setSpell(150544, { name = "Summon Random Favorite Mount", icon = 413588, known = true })
    end)

    it("describes the sentinel from its summon spell", function()
      local info = MM.Mounts.GetInfo(268435455)
      assert.equals("Summon Random Favorite Mount", info.name)
      assert.equals(413588, info.icon)
      assert.is_true(info.isCollected)
    end)

    it("is known and picks up the button by index 0", function()
      assert.is_true(MM.Mounts.IsKnown(268435455))
      assert.is_true(MM.Mounts.Pickup(268435455))
      assert.same({ type = "mount", id = 268435455 }, stubs.world.cursor)
    end)
  end)
end)
